# .github/workflows/tests.yml
name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches: [ '**' ]
    types: [ opened, synchronize, reopened ]
  release:
    types: [ published ]

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0

  test:
    name: Tests
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9 ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Poetry
      run: pip install poetry==1.1.9

    - name: Install dependencies
      run: poetry install

    - name: Run pytest
      run: poetry run python -m unittest discover -s src/tests -p '*_test.py'

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Poetry
      run: pip install poetry==1.1.9

    - name: Install dependencies
      run: poetry install

    - name: Run pytest
      run: poetry run coverage run --source ./src/grpc_argument_validator -m unittest discover -s src/tests -p '*_test.py'

    - name: Upload Coverage Report
      run: |
        poetry run coverage xml --fail-under=0
        poetry run codecov
