# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route_guide.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import enum_type_wrapper

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="route_guide.proto",
    package="routeguide",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x11route_guide.proto\x12\nrouteguide\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto"I\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12*\n\x04name\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue"I\n\tRectangle\x12\x1d\n\x02lo\x18\x01 \x01(\x0b\x32\x11.routeguide.Point\x12\x1d\n\x02hi\x18\x02 \x01(\x0b\x32\x11.routeguide.Point"\x8a\x01\n\x04\x41rea\x12(\n\trectangle\x18\x01 \x01(\x0b\x32\x15.routeguide.Rectangle\x12-\n\x07message\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12)\n\x04uuid\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.BytesValue")\n\x04Path\x12!\n\x06points\x18\x01 \x03(\x0b\x32\x11.routeguide.Point"0\n\x0bPlanetValue\x12!\n\x05value\x18\x01 \x01(\x0e\x32\x12.routeguide.Planet"\x8a\x01\n\x05Route\x12\x1e\n\x04path\x18\x01 \x01(\x0b\x32\x10.routeguide.Path\x12*\n\x04name\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\'\n\x06planet\x18\x03 \x01(\x0b\x32\x17.routeguide.PlanetValue\x12\x0c\n\x04tags\x18\x04 \x03(\t*?\n\x06Planet\x12\x12\n\x0ePLANET_INVALID\x10\x00\x12\x10\n\x0cPLANET_EARTH\x10\x01\x12\x0f\n\x0bPLANET_MARS\x10\x02\x32\x80\x01\n\x0cRouteService\x12\x38\n\x0b\x43reateRoute\x12\x11.routeguide.Route\x1a\x16.google.protobuf.Empty\x12\x36\n\nCreateArea\x12\x10.routeguide.Area\x1a\x16.google.protobuf.Emptyb\x06proto3',
    dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR, google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,],
)

_PLANET = _descriptor.EnumDescriptor(
    name="Planet",
    full_name="routeguide.Planet",
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name="PLANET_INVALID",
            index=0,
            number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="PLANET_EARTH",
            index=1,
            number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="PLANET_MARS",
            index=2,
            number=2,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=619,
    serialized_end=682,
)
_sym_db.RegisterEnumDescriptor(_PLANET)

Planet = enum_type_wrapper.EnumTypeWrapper(_PLANET)
PLANET_INVALID = 0
PLANET_EARTH = 1
PLANET_MARS = 2


_POINT = _descriptor.Descriptor(
    name="Point",
    full_name="routeguide.Point",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="x",
            full_name="routeguide.Point.x",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="y",
            full_name="routeguide.Point.y",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="name",
            full_name="routeguide.Point.name",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=94,
    serialized_end=167,
)


_RECTANGLE = _descriptor.Descriptor(
    name="Rectangle",
    full_name="routeguide.Rectangle",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="lo",
            full_name="routeguide.Rectangle.lo",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="hi",
            full_name="routeguide.Rectangle.hi",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=169,
    serialized_end=242,
)


_AREA = _descriptor.Descriptor(
    name="Area",
    full_name="routeguide.Area",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="rectangle",
            full_name="routeguide.Area.rectangle",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="message",
            full_name="routeguide.Area.message",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="uuid",
            full_name="routeguide.Area.uuid",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=245,
    serialized_end=383,
)


_PATH = _descriptor.Descriptor(
    name="Path",
    full_name="routeguide.Path",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="points",
            full_name="routeguide.Path.points",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=385,
    serialized_end=426,
)


_PLANETVALUE = _descriptor.Descriptor(
    name="PlanetValue",
    full_name="routeguide.PlanetValue",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="value",
            full_name="routeguide.PlanetValue.value",
            index=0,
            number=1,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=428,
    serialized_end=476,
)


_ROUTE = _descriptor.Descriptor(
    name="Route",
    full_name="routeguide.Route",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="path",
            full_name="routeguide.Route.path",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="name",
            full_name="routeguide.Route.name",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="planet",
            full_name="routeguide.Route.planet",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="tags",
            full_name="routeguide.Route.tags",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=479,
    serialized_end=617,
)

_POINT.fields_by_name["name"].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_RECTANGLE.fields_by_name["lo"].message_type = _POINT
_RECTANGLE.fields_by_name["hi"].message_type = _POINT
_AREA.fields_by_name["rectangle"].message_type = _RECTANGLE
_AREA.fields_by_name["message"].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_AREA.fields_by_name["uuid"].message_type = google_dot_protobuf_dot_wrappers__pb2._BYTESVALUE
_PATH.fields_by_name["points"].message_type = _POINT
_PLANETVALUE.fields_by_name["value"].enum_type = _PLANET
_ROUTE.fields_by_name["path"].message_type = _PATH
_ROUTE.fields_by_name["name"].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_ROUTE.fields_by_name["planet"].message_type = _PLANETVALUE
DESCRIPTOR.message_types_by_name["Point"] = _POINT
DESCRIPTOR.message_types_by_name["Rectangle"] = _RECTANGLE
DESCRIPTOR.message_types_by_name["Area"] = _AREA
DESCRIPTOR.message_types_by_name["Path"] = _PATH
DESCRIPTOR.message_types_by_name["PlanetValue"] = _PLANETVALUE
DESCRIPTOR.message_types_by_name["Route"] = _ROUTE
DESCRIPTOR.enum_types_by_name["Planet"] = _PLANET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Point = _reflection.GeneratedProtocolMessageType(
    "Point",
    (_message.Message,),
    {
        "DESCRIPTOR": _POINT,
        "__module__": "route_guide_pb2"
        # @@protoc_insertion_point(class_scope:routeguide.Point)
    },
)
_sym_db.RegisterMessage(Point)

Rectangle = _reflection.GeneratedProtocolMessageType(
    "Rectangle",
    (_message.Message,),
    {
        "DESCRIPTOR": _RECTANGLE,
        "__module__": "route_guide_pb2"
        # @@protoc_insertion_point(class_scope:routeguide.Rectangle)
    },
)
_sym_db.RegisterMessage(Rectangle)

Area = _reflection.GeneratedProtocolMessageType(
    "Area",
    (_message.Message,),
    {
        "DESCRIPTOR": _AREA,
        "__module__": "route_guide_pb2"
        # @@protoc_insertion_point(class_scope:routeguide.Area)
    },
)
_sym_db.RegisterMessage(Area)

Path = _reflection.GeneratedProtocolMessageType(
    "Path",
    (_message.Message,),
    {
        "DESCRIPTOR": _PATH,
        "__module__": "route_guide_pb2"
        # @@protoc_insertion_point(class_scope:routeguide.Path)
    },
)
_sym_db.RegisterMessage(Path)

PlanetValue = _reflection.GeneratedProtocolMessageType(
    "PlanetValue",
    (_message.Message,),
    {
        "DESCRIPTOR": _PLANETVALUE,
        "__module__": "route_guide_pb2"
        # @@protoc_insertion_point(class_scope:routeguide.PlanetValue)
    },
)
_sym_db.RegisterMessage(PlanetValue)

Route = _reflection.GeneratedProtocolMessageType(
    "Route",
    (_message.Message,),
    {
        "DESCRIPTOR": _ROUTE,
        "__module__": "route_guide_pb2"
        # @@protoc_insertion_point(class_scope:routeguide.Route)
    },
)
_sym_db.RegisterMessage(Route)


_ROUTESERVICE = _descriptor.ServiceDescriptor(
    name="RouteService",
    full_name="routeguide.RouteService",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=685,
    serialized_end=813,
    methods=[
        _descriptor.MethodDescriptor(
            name="CreateRoute",
            full_name="routeguide.RouteService.CreateRoute",
            index=0,
            containing_service=None,
            input_type=_ROUTE,
            output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="CreateArea",
            full_name="routeguide.RouteService.CreateArea",
            index=1,
            containing_service=None,
            input_type=_AREA,
            output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_ROUTESERVICE)

DESCRIPTOR.services_by_name["RouteService"] = _ROUTESERVICE

# @@protoc_insertion_point(module_scope)
