"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.wrappers_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Planet(_Planet, metaclass=_PlanetEnumTypeWrapper):
    pass
class _Planet:
    V = typing.NewType('V', builtins.int)
class _PlanetEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Planet.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    PLANET_INVALID = Planet.V(0)
    PLANET_EARTH = Planet.V(1)
    PLANET_MARS = Planet.V(2)

PLANET_INVALID = Planet.V(0)
PLANET_EARTH = Planet.V(1)
PLANET_MARS = Planet.V(2)
global___Planet = Planet


class Point(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    x: builtins.int = ...
    y: builtins.int = ...
    @property
    def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(self,
        *,
        x : builtins.int = ...,
        y : builtins.int = ...,
        name : typing.Optional[google.protobuf.wrappers_pb2.StringValue] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"name",b"name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"name",b"name",u"x",b"x",u"y",b"y"]) -> None: ...
global___Point = Point

class Rectangle(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LO_FIELD_NUMBER: builtins.int
    HI_FIELD_NUMBER: builtins.int
    @property
    def lo(self) -> global___Point: ...
    @property
    def hi(self) -> global___Point: ...
    def __init__(self,
        *,
        lo : typing.Optional[global___Point] = ...,
        hi : typing.Optional[global___Point] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"hi",b"hi",u"lo",b"lo"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"hi",b"hi",u"lo",b"lo"]) -> None: ...
global___Rectangle = Rectangle

class Area(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    RECTANGLE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    UUID_FIELD_NUMBER: builtins.int
    @property
    def rectangle(self) -> global___Rectangle: ...
    @property
    def message(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def uuid(self) -> google.protobuf.wrappers_pb2.BytesValue: ...
    def __init__(self,
        *,
        rectangle : typing.Optional[global___Rectangle] = ...,
        message : typing.Optional[google.protobuf.wrappers_pb2.StringValue] = ...,
        uuid : typing.Optional[google.protobuf.wrappers_pb2.BytesValue] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"message",b"message",u"rectangle",b"rectangle",u"uuid",b"uuid"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"message",b"message",u"rectangle",b"rectangle",u"uuid",b"uuid"]) -> None: ...
global___Area = Area

class Path(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    POINTS_FIELD_NUMBER: builtins.int
    @property
    def points(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Point]: ...
    def __init__(self,
        *,
        points : typing.Optional[typing.Iterable[global___Point]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"points",b"points"]) -> None: ...
global___Path = Path

class PlanetValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    VALUE_FIELD_NUMBER: builtins.int
    value: global___Planet.V = ...
    def __init__(self,
        *,
        value : global___Planet.V = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"value",b"value"]) -> None: ...
global___PlanetValue = PlanetValue

class Route(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PATH_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    PLANET_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    @property
    def path(self) -> global___Path: ...
    @property
    def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def planet(self) -> global___PlanetValue: ...
    @property
    def tags(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    def __init__(self,
        *,
        path : typing.Optional[global___Path] = ...,
        name : typing.Optional[google.protobuf.wrappers_pb2.StringValue] = ...,
        planet : typing.Optional[global___PlanetValue] = ...,
        tags : typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"name",b"name",u"path",b"path",u"planet",b"planet"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"name",b"name",u"path",b"path",u"planet",b"planet",u"tags",b"tags"]) -> None: ...
global___Route = Route
